### ISSUE TITLE
What android version is this kernel made for?

### ISSUE THREAD

**Issue by mati82821** [PixNDom/android_kernel_mediatek#1]
What android version is this kernel made for?

**Comment by pix106** [comment]
Android 5.0, it's what Lenovo released.
I tried using it, I did get a bootable kernel but with no display. System seemed to boot though, I could adb shell it and see a running Android. I tried with Android 5.1 - CM12.1, as prebuilt stock kernel was working fine with CM12.1.
Tell me what you get :)

**Comment by pix106** [comment]
(to trigger an email notification)

EDIT : my mistake, i don't know what THIS kernel source is made for, it's a test repo i had forgotten about.... I was refering to https://github.com/PixNDom/android_kernel_lenovo_Tab2A710F
Sorry :)

**Comment by huckleberrypie** [comment]
I presume this is the very same kernel you used when your CM12 build complained of sw_sync errors, yes?

**Comment by pix106** [comment]
no, all buidls use prebuilt stock kernel.
I never used these sources actually :)

**Comment by huckleberrypie** [comment]
Alright, was just wondering if anyone could help get my Epic to boot CM12 somehow. I could've just gotten away with CM11 but build issues kept me from doing so.
